import 'dart:convert';
import 'dart:io';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/pending_submission_model.dart';
import '../models/student_model.dart';
import '../models/user_model.dart';
import 'student_service.dart';
import 'storage_service.dart';

class OfflineQueueService {
  static const String _queueKey = 'pending_submissions';

  final StudentService _studentService;
  final StorageService _storageService;

  OfflineQueueService(this._studentService, this._storageService);

  // ── Save pending submission ──────────────────

  Future<void> save(PendingSubmissionModel submission) async {
    final prefs = await SharedPreferences.getInstance();
    final existing = await _loadAll(prefs);
    existing.add(submission);
    await _saveAll(prefs, existing);
  }

  // ── Load all pending ─────────────────────────

  Future<List<PendingSubmissionModel>> loadAll() async {
    final prefs = await SharedPreferences.getInstance();
    return _loadAll(prefs);
  }

  Future<List<PendingSubmissionModel>> _loadAll(SharedPreferences prefs) async {
    final raw = prefs.getStringList(_queueKey) ?? [];
    return raw
        .map((s) => PendingSubmissionModel.fromJson(
            jsonDecode(s) as Map<String, dynamic>))
        .toList();
  }

  Future<void> _saveAll(
      SharedPreferences prefs, List<PendingSubmissionModel> items) async {
    final raw = items.map((s) => jsonEncode(s.toJson())).toList();
    await prefs.setStringList(_queueKey, raw);
  }

  // ── Remove by ID ─────────────────────────────

  Future<void> remove(String localId) async {
    final prefs = await SharedPreferences.getInstance();
    final existing = await _loadAll(prefs);
    existing.removeWhere((s) => s.localId == localId);
    await _saveAll(prefs, existing);
  }

  // ── Sync all pending ─────────────────────────

  Future<void> syncAll(UserModel currentUser) async {
    final pending = await loadAll();
    if (pending.isEmpty) return;

    for (final submission in pending) {
      if (submission.isSyncing) continue;
      try {
        String photoUrl = '';

        // Upload photo if local path exists
        if (submission.localPhotoPath != null &&
            submission.localPhotoPath!.isNotEmpty) {
          final file = File(submission.localPhotoPath!);
          if (file.existsSync()) {
            final (url, _) = await _storageService.uploadStudentPhoto(
              imageFile: file,
              makerUid: currentUser.id,
            );
            photoUrl = url ?? '';
          }
        }

        // Build student model from stored data
        final data = Map<String, dynamic>.from(submission.studentData);
        final student = _studentFromMap(submission.localId, data, photoUrl);

        await _studentService.addStudent(student);
        await remove(submission.localId);
      } catch (_) {
        // Keep in queue — try again next time
      }
    }
  }

  /// Pending count for UI badge.
  Future<int> pendingCount() async {
    final all = await loadAll();
    return all.length;
  }

  StudentModel _studentFromMap(
      String localId, Map<String, dynamic> data, String photoUrl) {
    final now = DateTime.now().toUtc();
    return StudentModel(
      id: localId,
      serialNumber: 0, // will be generated by PostgreSQL
      firstName: data['firstName'] ?? data['first_name'] ?? '',
      middleName: data['middleName'] ?? data['middle_name'] ?? '',
      surname: data['surname'] ?? '',
      schoolName: data['schoolName'] ?? data['school_name'] ?? '',
      siblingClass: data['siblingClass'] ?? data['sibling_class'] ?? '',
      parents: data['parents'] ?? '',
      motherContact: data['motherContact'] ?? data['mother_contact'] ?? '',
      fatherContact: data['fatherContact'] ?? data['father_contact'] ?? '',
      fullAddress: data['fullAddress'] ?? data['full_address'] ?? '',
      area: data['area'] ?? '',
      otherArea: data['otherArea'] ?? data['other_area'] ?? '',
      landmark: data['landmark'] ?? '',
      otherLandmark: data['otherLandmark'] ?? data['other_landmark'] ?? '',
      photoUrl: photoUrl,
      makerUserId: data['makerUserId'] ?? data['maker_user_id'] ?? '',
      makerName: data['makerName'] ?? data['maker_name'] ?? '',
      submittedAt: data['submittedAt'] != null
          ? DateTime.tryParse(data['submittedAt'] as String) ?? now
          : now,
      isDeleted: false,
    );
  }
}
